version: '2'
services:
  d8-mysql:
    image: mysql:5.7
    volumes:
      - ../.data/db:/var/lib/mysql
      - ../db:/var/db # Used to import databases from command line
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal8
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  d8-apache:
    depends_on:
      - d8-mysql
    build: ./env/drupal8
    volumes:
      - ../web:/var/www/html
      - ../tmp/d8-apache:/tmp
    links:
      - d8-mysql
    ports:
      - "80:80"
    environment:
      D8_DB_HOST: d8-mysql:3306
      D8_DB_PASSWORD: dbpassword
      DRUPAL_VERSION: 8
      
  sandbox:
    depends_on:
      - d8-apache
    build: ./env/sandbox
    volumes_from:
      - d8-apache
    links:
      - d8-mysql
      - d8-apache
    tty: true
    environment:
      MYSQL_HOST: d8_mysql
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal8
      MYSQL_USER: user
      MYSQL_PASSWORD: password